
services:
  postgres:
    image: 'postgres:latest'
    container_name: my_postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: lib-container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data:
